import "./globals.css";

import CacheProviderMui from "@/config/CacheProvider";
import MuiThemeProvider from "@/theme/muiTheme";

export const metadata = {
  title: "Portfólio | Gustavo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MuiThemeProvider>
          {children}
        </MuiThemeProvider>
      </body>
    </html>
  );
}
